# Generated by Django 6.1.1 on 2026-09-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='shirt', help_text='Icon keyword (e.g. shirt, scissors, sparkle)', max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Ahilyanagar', max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('product_name', models.CharField(default='Menswear Collection', max_length=150)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_type', models.CharField(choices=[('STORE_PICKUP', 'Store Pickup (Delhi Gate, Ahilyanagar Showroom)'), ('HOME_DELIVERY', 'Express Home Delivery')], default='HOME_DELIVERY', max_length=30)),
                ('address_line', models.TextField(blank=True, help_text='House/Shop no, street, landmark')),
                ('city', models.CharField(default='Ahilyanagar', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, default='414001', max_length=10)),
                ('payment_method', models.CharField(choices=[('UPI_ONLINE', 'UPI / GPay / PhonePe / Paytm / Card'), ('COD', 'Cash on Delivery (COD)'), ('WHATSAPP_ORDER', 'Confirmed via WhatsApp Chat')], default='UPI_ONLINE', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Paid Successfully'), ('COD_VERIFIED', 'Cash on Delivery Verified')], default='PENDING', max_length=30)),
                ('order_status', models.CharField(choices=[('PLACED', 'Order Placed'), ('CONFIRMED', 'Order Confirmed'), ('PACKED', 'Packed & Ready'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Store Pickup'), ('DELIVERED', 'Delivered / Picked Up'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('badge', models.CharField(default='Ahilyanagar Exclusive', max_length=100)),
                ('button_text', models.CharField(default='Shop Menswear', max_length=50)),
                ('button_link', models.CharField(default='/products/', max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('fabric', models.CharField(default='100% Premium Cotton', help_text='e.g., 100% Giza Cotton, Denim with Elastane', max_length=100)),
                ('fit', models.CharField(choices=[('Slim Fit', 'Slim Fit'), ('Regular Fit', 'Regular Fit'), ('Relaxed Fit', 'Relaxed Fit'), ('Tailored Fit', 'Tailored Fit'), ('Standard', 'Standard Fit')], default='Slim Fit', max_length=50)),
                ('color', models.CharField(default='Classic', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original MRP in INR', max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, help_text='Special Offer / Selling Price in INR', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.CharField(blank=True, help_text='Direct URL for product photography', max_length=500)),
                ('image_2_url', models.CharField(blank=True, max_length=500)),
                ('image_3_url', models.CharField(blank=True, max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S (38)'), ('M', 'M (40)'), ('L', 'L (42)'), ('XL', 'XL (44)'), ('XXL', 'XXL (46)'), ('28', '28 (Waist)'), ('30', '30 (Waist)'), ('32', '32 (Waist)'), ('34', '34 (Waist)'), ('36', '36 (Waist)'), ('38', '38 (Waist)'), ('Free Size', 'Free Size')], max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
