# Generated by Django 6.1.1 on 2026-09-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a hero photo from your device', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='badge',
            field=models.CharField(default="Ahilyanagar's Exclusive Menswear Hub", max_length=100),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='button_text',
            field=models.CharField(default='Explore Collection', max_length=50),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or enter an image web URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='subtitle',
            field=models.CharField(default='Explore high-grade formal shirts, casual linen, stretch denim, and festival kurtas. Visit our showroom at Delhi Gate, Sarjepura or order online.', max_length=300),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='title',
            field=models.CharField(default='Upgrade Your Look With Premium Menswear', max_length=200),
        ),
    ]
