# Generated by Django 6.1.1 on 2026-09-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storebanner_image_alter_storebanner_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=10, help_text='Discount in percent (e.g. 10 for 10% off)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=500, help_text='Minimum cart subtotal to apply', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='Offer summary e.g. 10% OFF on all menswear', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_transaction_id',
            field=models.CharField(blank=True, help_text='UTR / UPI Ref Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('HOME_DELIVERY', 'Express Home Delivery'), ('STORE_PICKUP', 'Store Pickup (Delhi Gate, Ahilyanagar Showroom)')], default='HOME_DELIVERY', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay Online (Cards / UPI / NetBanking / Wallets)'), ('UPI_QR', 'Scan & Pay (Instant UPI QR)'), ('UPI_ONLINE', 'UPI / Online Payment'), ('COD', 'Cash on Delivery (COD)'), ('WHATSAPP_ORDER', 'Confirmed via WhatsApp Chat')], default='RAZORPAY', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Paid Successfully'), ('COD_VERIFIED', 'Cash on Delivery Verified'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=30),
        ),
    ]
