# Generated by Django 6.1.1 on 2026-09-30 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Used to verify purchase history', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='headline',
            field=models.CharField(blank=True, help_text='Short summary headline', max_length=150),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Approved for public display'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Verified Buyer badge'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating 1 to 5'),
        ),
    ]
