# Generated by Django 6.1.1 on 2026-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_user_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('HOME_DELIVERY', 'Express Home Delivery'), ('STORE_PICKUP', 'Store Pickup (Delhi Gate, Ahilyanagar Showroom)'), ('COUNTER_SALE', 'Showroom Walk-in Sale (Delhi Gate Counter)')], default='HOME_DELIVERY', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay Online (Cards / UPI / NetBanking / Wallets)'), ('UPI_QR', 'Scan & Pay (Instant UPI QR)'), ('IN_STORE_CASH', 'Showroom Cash Payment'), ('IN_STORE_UPI', 'Showroom Counter UPI (GPay / PhonePe QR Standee)'), ('IN_STORE_CARD', 'Showroom Card Swipe Machine'), ('UPI_ONLINE', 'UPI / Online Payment'), ('COD', 'Cash on Delivery (COD)'), ('WHATSAPP_ORDER', 'Confirmed via WhatsApp Chat')], default='RAZORPAY', max_length=30),
        ),
    ]
