# Generated by Django 6.1.1 on 2026-10-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_delivery_type_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Menu sorting position (e.g. 1 = first, 2 = second). Lower numbers appear first on the website.', verbose_name='Display Order / Sequence'),
        ),
    ]
