# Generated by Django 6.1.1 on 2026-10-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_notes',
            field=models.CharField(blank=True, help_text='Staff call verification notes', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='call_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Call'), ('VERIFIED', 'Call Verified & Confirmed'), ('UNREACHABLE', 'Unreachable / Not Answering'), ('FAKE', 'Fake / Invalid Order')], default='PENDING', help_text='Phone verification status before packing', max_length=20),
        ),
    ]
